name: clean_air
description: "Flutter project to show air and weather info in your position."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  google_fonts: 6.1.0
  weather: 3.1.1
  intl: 0.19.0
  http: 1.2.0
  permission_handler: 11.3.0
  geolocator: 11.0.0
  sliding_up_panel: 2.0.0+1
  diacritic: 0.1.5
  logger: 2.1.0
  path_provider: 2.1.2
  flutter_dotenv: 5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  lint: 2.3.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - config.env
